package com.coderhouse.petshop.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "PET")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class PetEntity {

  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  @Column(name = "ID")
  @Schema(description = "UUID Autogenerated", requiredMode = Schema.RequiredMode.AUTO, example = "0124529f-81b7-4924-952e-8d3fe108ab8f")
  private String id;

  @Column(name = "NAME", nullable = false)
  @Schema(description = "Pet's Name", requiredMode = Schema.RequiredMode.REQUIRED, example = "Firulais")
  private String name;

  @Column(name = "AGE", nullable = false)
  @Schema(description = "Pet's Age", requiredMode = Schema.RequiredMode.REQUIRED, example = "5")
  private Integer age;

  @Column(name = "TYPE", nullable = false)
  @Schema(description = "Pet's animal type", requiredMode = Schema.RequiredMode.REQUIRED, example = "Dog")
  private String type;

  @Column(name = "ADOPTED")
  @Schema(description = "If pet was adopted", example = "false")
  private boolean adopted;

  @ManyToOne()
  @JoinColumn(name = "USER_ID")
  @JsonIgnoreProperties("pets")
  private UserEntity adoptedBy;
}
